# Generated by Django 3.2.6 on 2021-09-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalissue',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalissue',
            name='volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
