# Generated by Django 3.2.6 on 2021-09-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_manuscriptauthorship_manuscript'),
        ('editor', '0004_alter_journalissue_manuscripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalissue',
            name='manuscripts',
            field=models.ManyToManyField(blank=True, related_name='issues', to='author.Manuscript'),
        ),
    ]
