# Generated by Django 3.2.6 on 2021-09-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_alter_journalissue_manuscripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalissue',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
