# Generated by Django 3.2.6 on 2021-09-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_alter_journalissue_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalissue',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
