# Generated by Django 3.2.6 on 2021-09-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_auto_20210917_1327'),
        ('editor', '0008_auto_20210919_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalissue',
            name='manuscripts',
            field=models.ManyToManyField(blank=True, related_name='issues', to='author.Manuscript'),
        ),
    ]
