# Generated by Django 3.2.6 on 2021-08-05 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETE', 'Complete'), ('EXPIRED', 'Expired')], default='ASSIGNED', max_length=20)),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Accept'), ('MINOR', 'Minor revision'), ('MAJOR', 'Major revision'), ('REJECT', 'Reject')], max_length=20, null=True)),
                ('date_due', models.DateTimeField()),
                ('date_submitted', models.DateTimeField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='author.revision')),
            ],
        ),
    ]
