# Generated by Django 3.2.6 on 2021-08-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_alter_review_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETE', 'Complete'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Manuscript was withdrawn')], default='ASSIGNED', max_length=20),
        ),
    ]
