# Generated by Django 3.2.6 on 2021-08-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('ACCEPT', 'Accept'), ('MINOR', 'Minor revision'), ('MAJOR', 'Major revision'), ('REJECT', 'Reject')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETE', 'Complete'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Manuscript was withdrawn'), ('EDIT_REQUESTED', 'Editing of review requested')], default='ASSIGNED', max_length=20),
        ),
    ]
