# Generated by Django 3.2.6 on 2021-08-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_auto_20210830_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='editor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
