# Generated by Django 3.2.6 on 2021-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_review_editor_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Manuscript was withdrawn'), ('EDIT_REQUESTED', 'Editing of review requested')], default='ASSIGNED', max_length=20),
        ),
    ]
