# Generated by Django 3.2.6 on 2021-09-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_editorial_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
