# Generated by Django 3.2.6 on 2021-09-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0008_auto_20210917_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_editorial_review',
        ),
    ]
