# Generated by Django 3.2.6 on 2021-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0009_remove_review_is_editorial_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
