# Generated by Django 3.2.6 on 2021-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0010_review_date_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Manuscript was withdrawn'), ('NOT_NEEDED', 'A decision was reached before this review was submitted'), ('EDIT_REQUESTED', 'Editing of review requested')], default='ASSIGNED', max_length=20),
        ),
    ]
