# Generated by Django 3.2.6 on 2021-08-05 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('revision_number', models.IntegerField()),
                ('revision_note', models.TextField(blank=True, null=True)),
                ('text', tinymce.models.HTMLField()),
                ('date_created', models.DateTimeField()),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNSUBMITTED', 'Unsubmitted'), ('WAITING_FOR_AUTHORS', 'Waiting for authors'), ('WITHDRAWN', 'Withdrawn'), ('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('MINOR', 'Minor revision'), ('MAJOR', 'Major revision'), ('REJECT', 'Reject')], default='PENDING', max_length=20)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='author.manuscript')),
            ],
        ),
        migrations.CreateModel(
            name='ManuscriptAuthorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.manuscript')),
            ],
        ),
        migrations.AddField(
            model_name='manuscript',
            name='authors',
            field=models.ManyToManyField(related_name='manuscripts', through='author.ManuscriptAuthorship', to=settings.AUTH_USER_MODEL),
        ),
    ]
