# Generated by Django 3.2.6 on 2021-08-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscriptauthorship',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
