# Generated by Django 3.2.6 on 2021-08-06 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0003_auto_20210806_1626'),
        ('reviewer', '0002_manuscriptreviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewed_manuscripts', through='reviewer.ManuscriptReviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revision',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='status',
            field=models.CharField(choices=[('UNSUBMITTED', 'Unsubmitted'), ('WAITING_FOR_AUTHORS', 'Waiting for authors'), ('WITHDRAWN', 'Withdrawn'), ('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('MINOR', 'Minor revision'), ('MAJOR', 'Major revision'), ('REJECT', 'Reject'), ('PUBLISHED', 'Published')], default='PENDING', max_length=20),
        ),
    ]
