# Generated by Django 3.2.6 on 2021-09-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_manuscriptauthorship_manuscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='status',
            field=models.CharField(choices=[('UNSUBMITTED', 'Unsubmitted'), ('WAITING_FOR_AUTHORS', 'Waiting for authors'), ('WITHDRAWN', 'Withdrawn'), ('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('MINOR', 'Minor revision'), ('MAJOR', 'Major revision'), ('REJECT', 'Reject'), ('PUBLISHED', 'Published')], default='UNSUBMITTED', max_length=20),
        ),
    ]
