# Generated by Django 3.2.6 on 2021-09-17 13:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_alter_revision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='editorial_review',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='revision_note',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
