# Generated by Django 3.2.6 on 2021-09-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rename_is_teacher_profile_is_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
